# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5192e8dac3d42cc5358eff42e73f894887f40a7d528458db86597e61fb2ecbdb6a36d319a8a493b29c7040c8b40ef5a0d1d84949a66bd8db3cbff19196c093c7

test:
  secret_key_base: 2cae33f6bf00c638669635528e8c1d33f4a2685a0548a007b2f95fe9a519fbbed449ad8ad9aa2fc65a9e5534e6a57d8ad26e52ffb654220683b01f7c0e146c24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
